### AddUserRole
# @import ./PreScript.http
# @forceRef PreRequest

POST /AddUserRole
    ?id=2
    &role=Developer
Content-Type: application/json

?? status == 204

### GetUsers
GET /GetUsers

?? body length == 3
?? js response.parsedBody[1].RolesNme.length == 3
?? js response.parsedBody[1].Roles[2] == Developer