# @import ./PreScript.http
# @forceRef PreRequest
### AddUser_Repeated

POST /AddUser
Content-Type: application/json

{
    "Name": "Joe",
    "Mobile": "09121234567"
}

?? status == 400
?? body contains This user already