### AddUserStaff
# @import ./PreScript.http
# @forceRef PreRequest
POST /AddUserStaff
    ?id=1
    &staffId=1
Content-Type: application/json

?? status == 204

### GetUsers
GET /GetUsers

?? body length == 2
?? js response.parsedBody[0].Staffs.length == 2
?? js response.parsedBody[0].Staffs[1].Name == Modir Fanni