# @import ./PreScript.http
# @forceRef PreRequest
### AddUserStaff

POST /AddUserStaff
    ?id=1
    &staffId=1
Content-Type: application/json

?? status == 204

### GetUsers
GET /GetUsers
Cookie: Claims={{claims}};Token=${{token}};Database={{database}}

?? body length == 2
?? js response.parsedBody[0].Staffs.length == 2
?? js response.parsedBody[0].Staffs[1] == Modir Mali