# @import ./PreScript.http
### AddUser

POST /AddUser
Content-Type: application/json

{
    "Name": "Frank",
    "Mobile": "09121234567"
}

?? status == 200
?? body id > 0

### GetUsers
GET /GetUsers
Content-Type: application/json

?? body length == 3
?? js response.parsedBody[2].Name == Frank