# @import ./PreScript.http
# @forceRef PreRequest
### AddUserRole

POST /AddUserRole
    ?id=2
    &role=Developer
Content-Type: application/json

?? status == 204

### GetUsers
GET /GetUsers

?? body length == 3
?? js response.parsedBody[1].Roles.length == 1
?? js response.parsedBody[1].Roles[1] == Developer