# @import ./PreScript.http
### AllowStaffRole

POST /AllowStaffRole
    ?id=2
    &staffId=1
    &role=Admin

?? status == 204

### GetUsers
GET /GetUsers

?? js response.parsedBody[1].DeniedRoles.length == 0