# @import ./PreScript.http
# @forceRef PreRequest
### AllowStaffRole

POST /AllowStaffRole
    ?id=2
    &staffId=1
    &role=Admin

?? status == 204

### GetUsers
GET /GetUsers
Cookie: Claims={{claims}};Token=${{token}};Database={{database}}

?? js response.parsedBody[1].DeniedRoles.length == 0