# @import ./PreScript.http
# @forceRef PreRequest
### DenyStaffRole

PUT /DenyStaffRole
    ?id=1
    &staffId=2
    &role=Admin
Content-Type: application/json

?? status == 204

### GetUsers
GET /GetUsers
Cookie: {{cookie}}

?? body length == 3
?? js response.parsedBody[0].DeniedRoles[0] == Admin