# @import ./PreScript.http
### GetRoles

GET /GetRoles

?? status == 200

{{
const {expect} = require('chai');

test("Role", function () {
    var jsonData = JSON.parse(response.body);
    expect(jsonData).to.have.lengthOf(5);
    expect(jsonData[0].Name).to.eql("Manager");
});
}}