# @import ./PreScript.http
### GetStaffs

GET /GetStaffs

?? status == 200
?? js response.parsedBody[0].Name == Modir Mali
?? js response.parsedBody[0].Roles.length == 1
?? js response.parsedBody[0].Roles[0] == Admin