# @import ./PreScript.http
# @forceRef PreRequest
### RemoveUserStaff

PUT /RemoveUserStaff
    ?id=1
    &staffId=2

?? status == 204

### GetUsers
GET /GetUsers
Cookie: Claims={{claims}};Token=${{token}};Database={{database}}

?? js response.parsedBody[0].Staffs.length == 0