# @import ./PreScript.http
# @forceRef PreRequest
### RemoveUserRole

PUT /RemoveUserRole
    ?id=2
    &role=Manager

?? status == 204

### GetUsers
GET /GetUsers
Cookie: {{cookie}}

?? js response.parsedBody[1].Roles.length == 0