# @import ./PreScript.http
### RemoveUserRole_Fail

PUT /RemoveUserRole
    ?id=1
    &role=Manager

?? status == 400

{{
const {expect} = require('chai');

test("Message", function () {
    expect(response.body).to.be.equal("User has not this role");
});
}}