# @import ./PreScript.http
# @forceRef PreRequest
### RemoveUserStaff

PUT /RemoveUserStaff
    ?id=1
    &staffId=2

?? status == 204

### GetUsers
GET /GetUsers

?? js response.parsedBody[0].Staffs.length == 0