# @import ./PreScript.http
### RemoveUserStaff

PUT /RemoveUserStaff
    ?id=1
    &staffId=2

?? status == 204

{{
 const axios = require('axios');
 const {expect} = require('chai');

 const wait = axios.get(`${host}/GetUsers`).then(response => {
        test("Check", () => {
        var jsonData = response.data
        let targetUser = jsonData.filter(user => user.ID === 1);
        expect(targetUser[0].Staffs).to.have.lengthOf(0);
    });
    })

    exports.wait = wait;
}}